# Generated by Django 3.2.4 on 2023-11-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='dispositivo',
            field=models.CharField(db_column='dispositivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='frecuencia',
            field=models.CharField(db_column='frecuencia', max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='gama',
            field=models.CharField(db_column='gama', max_length=35),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='met_pago',
            field=models.CharField(db_column='met_pago', max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tiempo_nave',
            field=models.CharField(db_column='tiempo_nav', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrou',
            name='id_registroU',
            field=models.AutoField(db_column='id_registro', primary_key=True, serialize=False),
        ),
    ]
